# Generated by Django 4.2.10 on 2024-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/products/default.jfif', upload_to='images/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
