# Generated by Django 4.2.10 on 2024-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='total_price_gte_0',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='total_price_gte_0'),
        ),
    ]
